### ISSUE TITLE
Build fails under latest unstable-small branch

### ISSUE THREAD

**Issue by enderger** [cole-h/agenix-rs#5]
Hey,

It seems that one of the dependencies of this project uses `stdenv.lib` (I've reported it to `nixpkgs-mozilla` already, hopefully a fix comes soon), and as such prevents building on the current `unstable-small` branch. The current workaround is to force this to follow stable, since the alias still exists.

**Comment by enderger** [comment]
Since the team seems to be lazy on merging a PR which fixes the issue, I'd probably suggest (for now) moving over to the Fenix project's Rust builds.

**Comment by cole-h** [comment]
We already follow stable: https://github.com/cole-h/agenix-cli/blob/124ddbd7b93fe02e59dec622f8085d41217c71b5/flake.nix#L4 (or, at least, that was stable at the time). Builds should work fine as long as you don't override the `nixpkgs` input used by this project to be e.g. `follows = "some other nixpkgs";`

I'd probably accept a PR moving this to `fenix`, but I don't have the time to explore this myself :(

(Sorry for taking so long to reply to this -- been a fair bit busy)

**Comment by cole-h** [comment]
(Feel free to re-open if you still experience issues.)
